#ifndef COMMUNSPRITES_H
#define COMMUNSPRITES_H
#include "GameControlers/sprites.h"
#include <lcom/lcf.h>

// xpm files
#include "xpm/Aim-Menu.xpm"
#include "xpm/MainMenu.xpm"
#include "xpm/ReactionTime_click.xpm"
#include "xpm/ReactionTime_start.xpm"
#include "xpm/ReactionTime_time.xpm"
#include "xpm/ReactionTime_toosoon.xpm"
#include "xpm/ReactionTime_waitforgreen.xpm"
#include "xpm/aim.xpm"
#include "xpm/letters/a.xpm"
#include "xpm/letters/b.xpm"
#include "xpm/letters/c.xpm"
#include "xpm/letters/d.xpm"
#include "xpm/letters/e.xpm"
#include "xpm/letters/f.xpm"
#include "xpm/letters/g.xpm"
#include "xpm/letters/h.xpm"
#include "xpm/letters/i.xpm"
#include "xpm/letters/j.xpm"
#include "xpm/letters/k.xpm"
#include "xpm/letters/l.xpm"
#include "xpm/letters/m.xpm"
#include "xpm/letters/n.xpm"
#include "xpm/letters/o.xpm"
#include "xpm/letters/p.xpm"
#include "xpm/letters/q.xpm"
#include "xpm/letters/r.xpm"
#include "xpm/letters/s.xpm"
#include "xpm/letters/t.xpm"
#include "xpm/letters/u.xpm"
#include "xpm/letters/v.xpm"
#include "xpm/letters/w.xpm"
#include "xpm/letters/x.xpm"
#include "xpm/letters/y.xpm"
#include "xpm/letters/z.xpm"
#include "xpm/mouse.xpm"
#include "xpm/numbers/eight.xpm"
#include "xpm/numbers/equal.xpm"
#include "xpm/numbers/five.xpm"
#include "xpm/numbers/four.xpm"
#include "xpm/numbers/nine.xpm"
#include "xpm/numbers/one.xpm"
#include "xpm/numbers/seven.xpm"
#include "xpm/numbers/six.xpm"
#include "xpm/numbers/slash.xpm"
#include "xpm/numbers/three.xpm"
#include "xpm/numbers/two.xpm"
#include "xpm/numbers/two_points.xpm"
#include "xpm/numbers/zero.xpm"
#include "xpm/target.xpm"

// React Menu
Sprite *black_background;
Sprite *react_Start;
Sprite *react_Wait;
Sprite *react_ToSoon;
Sprite *react_Click;
Sprite *react_Restart;
// Aim Menu
Sprite *aim_menu;
Sprite *aim_menu_background;
// Main Menu
Sprite *main_menu;
Sprite *main_menu_background;
// Sprites
Sprite *aim_sprite;
Sprite *mouse_sprite;
Sprite *target_Sprite;
Sprite *target_background;
Sprite *background;
Sprite *red_background;
// Numbers
Sprite *one_sprite;
Sprite *two_sprite;
Sprite *three_sprite;
Sprite *four_sprite;
Sprite *five_sprite;
Sprite *six_sprite;
Sprite *seven_sprite;
Sprite *eight_sprite;
Sprite *nine_sprite;
Sprite *zero_sprite;
Sprite *two_points_sprite;
Sprite *equal_sprite;
Sprite *slash_sprite;
// Letters
Sprite *A_sprite;
Sprite *B_sprite;
Sprite *C_sprite;
Sprite *D_sprite;
Sprite *E_sprite;
Sprite *F_sprite;
Sprite *G_sprite;
Sprite *H_sprite;
Sprite *I_sprite;
Sprite *J_sprite;
Sprite *K_sprite;
Sprite *L_sprite;
Sprite *M_sprite;
Sprite *N_sprite;
Sprite *O_sprite;
Sprite *P_sprite;
Sprite *Q_sprite;
Sprite *R_sprite;
Sprite *S_sprite;
Sprite *T_sprite;
Sprite *U_sprite;
Sprite *V_sprite;
Sprite *W_sprite;
Sprite *X_sprite;
Sprite *Y_sprite;
Sprite *Z_sprite;

#endif // COMMUNSPRITES_H
